modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/JustAHuman-xD/CobblemonConservation/issues"
license = "All Rights Reserved"

[[mods]]
modId = "cobblemonconservation"
version = "${version}"
displayName = "CobblemonConservation"
authors = "JustAHuman"
description = '''
A simple serverside mod that prevents specific pokemon from despawning (or allows a timer despawn)
'''
displayURL = "https://github.com/JustAHuman-xD/CobblemonConservation"

[[dependencies.cobblemonconservation]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.cobblemonconservation]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.cobblemonconservation]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "SERVER"

[[mixins]]
config = "cobblemonconservation.mixins.json"